# Generated by Django 3.1.2 on 2020-10-14 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BancadaIA', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experimentospotnano',
            old_name='text',
            new_name='codigo',
        ),
    ]
