# Generated by Django 3.1.2 on 2020-11-07 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentoGangorra',
            fields=[
                ('experimento_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('csvArquivo', models.FileField(null=True, upload_to='gangorra/csv/', verbose_name='')),
                ('videoArquivo', models.FileField(null=True, upload_to='gangorra/videos/', verbose_name='')),
                ('modelo_kp', models.CharField(default='0', max_length=20)),
                ('modelo_ki', models.CharField(default='0', max_length=20)),
                ('modelo_kd', models.CharField(default='0', max_length=20)),
                ('modelo_referencia', models.CharField(default='0', max_length=20)),
                ('modelo_repeticoes', models.CharField(default='0', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
